rm sidechain.aux
rm sidechain.out
rm sidechain.log
rm sidechain.bbl
rm sidechain.blg
pdflatex sidechain
bibtex sidechain
pdflatex sidechain
pdflatex sidechain
rm sidechain.aux
rm sidechain.out
rm sidechain.log
rm sidechain.bbl
rm sidechain.blg
